package com.dur.shared;

public enum Constants {
	REQUEST_TYPE, latitude, longitude, POISON_PILL, CLIENT_PHONE, CLIENT_BT_ID, CLIENT_IP_ADDRESS, SENDER_ID, RECIPIENT_ID, DISPLAY_NAME, INITIAL_MESSAGES, SERVER_ADDRESS, IP_PORT, CHANNEL, PATH
}
